### PR TITLE
Persistent Storage & Stats Calculation

### PR DESCRIPTION
**Pull request by JonathanGrant92**
Merge Seb2 pr #65 first before review. I merged Seb2 into this branch already to mitigate merge conflicts.

### CODE REVIEW

**Comment by JonathanGrant92** [comment]
Will fix DeepScan issues within one week. No guarantee I will get to this tomorrow.

**Review by NoelC9 — APPROVED** [review]
Thanks for adding comments. Looks good!

**Comment by JonathanGrant92** [comment]
> Thanks for adding comments. Looks good!

I didn't add most of the doc string. That was another pr, by Sebastian.

**Review by seboss123 — APPROVED** [review]
Fantastic, great comments and works well!

**Pull request merged**
