### PR TITLE
feat: readme files. moved existing image files to thumbnail/ under assets/.

### PR DESCRIPTION
**Pull request by JonathanGrant92**
Small changes and some new directories.

### CODE REVIEW

**Comment by seboss123** [comment]
Did we still want to merge this?

**Comment by JonathanGrant92** [comment]
> Did we still want to merge this?

We can merge this once I fix failing checks. I will have this task marked down for this week. I will let you know when I have more. Currently, I need to merge commit history of main into this branch, so I don't overwrite recent pull requests.

**Comment by JonathanGrant92** [comment]
> Did we still want to merge this?

Yeah, this is ready for review and merge.

**Review by NoelC9 — APPROVED** [review]
Changes look good

**Review by SebastianSafaiRad — APPROVED** [review]

**Pull request merged**
