### PR TITLE
Implemented alarm scheduling and notification display

### PR DESCRIPTION
**Pull request by seboss123**
To run you will need to use the command "expo run:android"

### CODE REVIEW

**Review by JonathanGrant92 — COMMENTED** [review]
Do we need to share `android/app/debug.keystore`?

**Comment by seboss123** [comment]
> Do we need to share `android/app/debug.keystore`?

Unsure if we need to share it. From this [link](https://www.geeksforgeeks.org/where-is-debug-keystore-in-android-studio/) it seems the build process creates it

**Comment by seboss123** [comment]
QR preview will not show alarm functionality because it doesn't compile custom native code. In order to run it switch to my branch and use "expo run:android" then alarm functionality will work

**Review by JonathanGrant92 — CHANGES_REQUESTED** [review]
There exists two binary files I don't think we need to share:   
1. `android/app/debug.keystore`
2. `android/gradle/wrapper/gradle-wrapper.jar`

**Comment by JonathanGrant92** [comment]
> > Do we need to share `android/app/debug.keystore`?
> 
> Unsure if we need to share it. From this [link](https://www.geeksforgeeks.org/where-is-debug-keystore-in-android-studio/) it seems the build process creates it

If that's the case, the build process generates the file, then we do not need to add the binary file to the repo.

**Comment by JonathanGrant92** [comment]
Everything else looks good. So, remove two binary files and try setting `android:usesCleartextTraffic=` to false. If setting it to false breaks the build, then we can set the status of the hotspot to `Safe` in SonarCloud.

Nice refactor of Stats. I see that fixed the bug with updating the Stats view.

**Review by JonathanGrant92 — APPROVED** [review]

**Review by NoelC9 — APPROVED** [review]

**Pull request merged**
